version: '3.9'

services:
  mysql:
    image: mysql:8
    platform: linux/amd64
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_DATABASE=news-feed

volumes:
  mysql-data:
    driver: local